### ISSUE TITLE
Decide on (and test) potentially per-calendar behavior near extreme date values

### ISSUE THREAD

**Issue by Manishearth** [unicode-org/icu4x#7076]
Our calendars currently use `i32` year values, and there are a couple ways that that can cause arithmetic overflow. The simplest way is when converting between different eras: `i32::MAX reiwa` is going to be an out-of-range extended_year. More subtle cases happen due to use of various calendars for internal calculation, or things like "get the R.D. as milliseconds". Some of these cases can be solved by using wider integer types, but by and large `i32::MAX` is not really a useful year to try and shove into this API.

We should _ideally_ never be debug asserting in a way reachable to users.

https://github.com/unicode-org/icu4x/pull/7062 attempts to improve the situation by adding coarse guards to pan-Calendar construction APIs: all `year`/`extended_year` inputs to `from_fields`/`from_codes` are now checked to be within ±2²⁷. It does not attempt to do anything about `Date::try_new_from_specificcalendar`, calendar conversions, or calendar arithmetic.

https://github.com/unicode-org/icu4x/pull/7065 goes further to remove most sources of overflow errors except the small ones really close to `i32::MAX`. There's an open question there about Chinese: whether we should do millisecond math in i128, or error on those large dates.

We can and should try and expand the coarse year range. @robertbastian thinks we can get it to be ±2³⁰ (`i32::MAX / 2`). That would in and of itself be quite good, I think it would require us to run the simple chinese approximation in i128.

Regardless of the expansion of the range, we have some decisions to make. Note that all of these basically impact _really large_ dates, which don't necessarily actually matter too much. It mostly matters that applications can use this code without experiencing strange behavior when users input overlarge dates.

The main one is that whether these ranges should be per calendar or pan-calendar. Per calendar means that we can be more or less liberal for individual calendars, pan calendar means that all calendars. This would mean that calendar conversions cannot be used to produce dates that cannot be directly produced, and thus all dates continue to roundtrip without error.

#7062 avoids the question by making it an _input_ constraint on specific APIs: it's not really trying to figure out whether it should be per-calendar or pan-calendar, it is just saying that any `year` input on a pan-calendar API has a rough constraint.

If we decide it should be per-calendar, what happens on calendar conversion?

In either case, what happens on out-of-range duration arithmetic?

Note that these answers are entangled with implementation detail: it's not sufficient to say that we have per-calendar R.D. ranges, because from an implementation perspective you may need to guard against something _before_ you have an R.D. to work with.

**Comment by Manishearth** [comment]
ugh, typed up a whole issue body and then clicked cancel by accident

**Comment by Manishearth** [comment]
> Note that these answers are entangled with implementation detail: it's not sufficient to say that we have per-calendar R.D. ranges, because from an implementation perspective you may need to guard against something before you have an R.D. to work with.



Generally this reason is why I think the only strategy we should have is the current one of restricting _inputs_: if someone creates an "out of range" date by calendar conversion, that's fine: it's not going to be too much larger than the range min/max. It's also better for documentation, when a calendar (or the crate) can declare the valid range for `year` or `extended_year`.

We can decide on whether the input restriction needs to be global or per calendar, or per-API even.

**Comment by Manishearth** [comment]
cc @sffc

**Comment by sffc** [comment]
I remember at some point I had a RataDie limit that was i64 / 256 or something, in order to give "plenty" of room for transient calculations to use more bits in the RataDie.

We complain about Temporal's limits a lot, and it "only" requires 200k years. We don't need to go too much higher than that.

I had suggested 1e6 extended years, because I prefer round numbers in the Decimal system for human-imposed limits.

**Comment by Manishearth** [comment]
> We complain about Temporal's limits a lot, and it "only" requires 200k years. We don't need to go too much higher than that.


FWIW I complain about Temporal's limits there because it is a _spec_ and it mandates particular behavior there. I think specifications should be very careful about what they mandate, and it feels silly to mandate 200k years when most of the calendars do not have meaning in that range.

As a library I am more willing to try and exercise some freedom here. It's _nice_ for our ISO calendar at least to have as much validity as possible. I'm not strongly on the side of "let's have a huge validity range", but it seems like if it's easy to attain, why not?

**Comment by sffc** [comment]
I'd be fine making the limit RD-based instead of year-based.

+/- 1e8 RD? (the smallest power of 10 that is greater than the Temporal limit)

Each calendar is required to return an error when attempting to construct a value exceeding that limit. This can be implemented cleanly for most ICU4X calendars by adding a trait method to CalendarArithmetic and then checking the ranges in the ArithmeticDate constructor.

Date::try_from_fields continues to enforce its safe extended year range to a number that exceeds the limits of the RD range in all calendars. I think 1e6 still works if the RD limit is 1e8.

To summarize:

1. User calls Date::try_from_fields.
2. Date::try_from_fields checks in a calendar-agnostic way whether the extended or era year exceeds +/- 1e6. If it does, it immediately returns a RangeError.
3. Date::try_from_fields calls calendar-specific code to convert the given fields to a calendar YMD.
4. Date::try_from_fields calls calendar-specific code to check whether the calendar YMD, when converted to a RD, is within RD +/- 1e8. Calendars can optimize this check to avoid actually converting to an RD. If the check fails, return a RangeError.
5. Done, return an Ok result.

**Comment by Manishearth** [comment]
I think that's a decent plan, and I appreciate the implementation details (since they're a part of the challenge here) The two-part range check on years _and_ on RDs would make it work. We'd need to be careful to insert the RD checks in all the right places, but it's doable.

**Comment by sffc** [comment]
My post above focuses on `try_from_fields` (and `try_new_from_codes` which is a wrapper over `try_from_fields`). To address the other constructors (CC @robertbastian):

- `from_rata_die` is infallible. This suggests that RataDie's constructors should enforce the same range. Unfortunately `RataDie::new` is also infallible. (This is an example of why I really didn't want to graduate RataDie as part of icu_calendar's API.) So, we should mark either `Date::from_rata_die` or `RataDie::new` as deprecated and introduce a fallible variant.
- `new_from_iso` is infallible. This is fine, because `Date<Iso>` complies by these same bounds.
- `from_raw` should probably be named `from_raw_unchecked` to emphasize that it is skipping invariant checks and can produce panicky code. I suggest a deprecate-and-rename.
- `try_new_buddhist`, `try_new_coptic`, ... are already fallible, and they share _some_ code with `try_from_fields`, so the bounds check should be implementable in those constructors.

**Comment by Manishearth** [comment]
Slight preference for deprecating `from_rata_die`, but I recognize that's much more churn than deprecating `RataDie::new()`. I'd like `calendrical_calculations` to not be beholden to any RD limits if possible.

> from_raw should probably be named from_raw_unchecked to emphasize that it is skipping invariant checks and can produce panicky code. I suggest a deprecate-and-rename.


Is it even possible to make a raw `SomeCalendar::Inner` from outside of `icu_calendar`? Most of these types are internally private and unconstructible, IIRC.

**Comment by robertbastian** [comment]
`from_rata_die` already saturates at the range of `ArithmeticDate`, we can just have it saturate in a tighter range. I do not want to deprecate it.

> Is it even possible to make a raw SomeCalendar::Inner from outside of icu_calendar?

No

**Comment by robertbastian** [comment]
If we limited years to 2^23 (or 2^20 if we want to be more round), we could pack an `ArithmeticDate` into 4 bytes. Months need 4 bits, days need 5. This would require a little work when `YearInfo` is not `i32`, but I think it's feasible.

**Comment by robertbastian** [comment]
`add` will also have to either saturate or return errors when it leaves the safe range.

**Comment by sffc** [comment]
Seeking consensus on the following:

- `Date` is defined to be any date between two specific RataDies, `MIN` and `MAX`.
- All fallible functions in `icu_calendar` that return a `Date` must enforce this range and return an error if the input parameters would produce an RD exceeding this limit.
- The only known infallible function that could return an out-of-bounds Date is `Date::from_rata_die`. It should saturate the RD to be between `MIN` and `MAX`.

Corollaries:

- `Date::add` can and should exit early if the resulting Date would be out of range (#7077, #7207)
- Calendar-specific code can assume that it is never given an RD that is too much bigger (~1 order of magnitude) than `MIN` and `MAX`. For example, the EastAsianTraditional approximation can continue to use debug-panicky math.

Open for discussion:

- `MIN` is -1e8 RD, `MAX` is +1e8 RD.
- Add a new function `Date::try_from_rata_die` that returns an error if the RD is out of range.
    - The error variant could have a saturation convenience function: `Date::try_from_rata_die(rd).unwrap_or_else(DateFromRataDieError::saturate)`
    - Or it could return a custom `Result` that derefs to a normal `Result` but adds a saturation function: `Date::try_from_rata_die(rd).unwrap_or_saturate()`
- Also deprecate `Date::from_rata_die`.

**Comment by robertbastian** [comment]
> * MIN is -1e8 RD, MAX is +1e8 RD.

I'd rather anchor this in round Gregorian dates than round Rata Die. I'd also prefer using a power of 2.

> * Add a new function `Date::try_from_rata_die` that returns an error if the RD is out of range.
>   
>   * The error variant could have a saturation convenience function: `Date::try_from_rata_die(rd).unwrap_or_else(DateFromRataDieError::saturate)`
>   * Or it could return a custom `Result` that derefs to a normal `Result` but adds a saturation function: `Date::try_from_rata_die(rd).unwrap_or_saturate()`
> * Also deprecate `Date::from_rata_die`.

If we expose the bounds somewhere (`Date::MAX_RATA_DIE`), clients can do that check themselves if they really want to. In general I'd rather not make functions fallible just for the purpose of date range, because then callers that do normal things have to handle failures every single time.

With bit packing, the lowest representable date would be RD -2\*\*22*365.25+1 (365.25 is the longest average year length of any calendar), which is larger in magnitude than both 1e10 and 2**30.

**Comment by Manishearth** [comment]
Broadly in favor of this plan.

Don't have strong opinion on min/max RD.

**Comment by sffc** [comment]
I want the bounds to be big enough to handle known users and not much bigger than that. Temporal is the known user with the largest range.

It appears #7219 makes the limit RD +/- 366e6, which is on the same order of magnitude that I had previously suggested (1e8), so it seems _fine_ to me. I think I prefer using a "round" number in RD space rather than ISO Year space given that the bound is pan-calendar RD-based.

**Comment by Manishearth** [comment]
FWIW the bound is also pan-calendar extended-year based in from_fields, but that is not the fundamental invariant, it constrains further than the fundamental invariant.

**Comment by Manishearth** [comment]
Actually no, sorry, the year range is the fundamental invariant. The RD range is not fundamental, it just provides a way of doing an early prefilter.

So it makes sense for the year range to be "round"

**Comment by sffc** [comment]
A more detailed review of #7219 suggests that the range is two-part: an extended year range of 1e6, coupled with an RD range of 3.66e8, where different constructors use different ranges. I left a comment in the PR asking whether we want to use a consistent range. There's also an assumption I haven't verified that the extended year range is narrower than the RD range in every calendar.

**Comment by Manishearth** [comment]
@sffc No, the RD range is just an early check: `from_rata_die` is the only constructor applying the RD range, and that calls down to calendar code, which _then_ will apply the year range.

Like I said, the year range is fundamental, the RD range is a prefilter. Its job is to avoid "mathematically problematic" values from reaching calendar-specific code. Calendar-specific code may then apply the real year range.

**Comment by sffc** [comment]
> There's also an assumption I haven't verified that the extended year range is narrower than the RD range in every calendar.

For example, is the Ethiopic Amete Alem date (-1e6, 1, 1) within the RD range? I think maybe it isn't. Haven't verified 100%.

**Comment by sffc** [comment]
> [@sffc](https://github.com/sffc) No, the RD range is just an early check: `from_rata_die` is the only constructor applying the RD range, and that calls down to calendar code, which _then_ will apply the year range.

No, it calls a `calendrical_calculations` function and then uses `ArithmeticDate::new_unchecked`. The ranges are constructor-dependent.

**Comment by Manishearth** [comment]
> No, it calls a calendrical_calculations function and then uses ArithmeticDate::new_unchecked. The ranges are constructor-dependent.


Oh, you're talking about the individual from_rata_die impls.

Yeah that's exactly what I was talking about when I said I'm not fully convinced yet in https://github.com/unicode-org/icu4x/pull/7219#issuecomment-3493164700 :) But it was something I planned to go through and verify properly later.

Perhaps ArithmeticDate::new_unchecked should be clamping `year`?

The only problem is that cross-calendar conversions will be wobbly then. I'm kind of okay with that?

As mentioned in your plan above we should be deprecating `from_rata_die` anyway.

I would prefer for there to be a single fundamental range being applied. Perhaps in that case it must be R.D, but that forces us to check R.D. on all construction.

**Comment by robertbastian** [comment]
The RD range is the fundamental range, the invariant in ArithmeticDate is that the date it represents is inside the RD range. 

The year range is tighter than the RD range, for the purpose of communicating clear cross-calendar valid year ranges in constructors. If we applied RD ranges to YMD constructors, every calendar's constructor would have different ranges, and the ranges would not be on year boundaries. It's possible to create the max Gregorian date and convert that to Hebrew, whereas directly constructing this Hebrew date is impossible. We could allow it, but the added complexity in the constructor documentation is not worth it imho.

**Comment by Manishearth** [comment]
> The year range is tighter than the RD range

Doesn't this mean that there are dates which can be constructed but will not roundtrip with themselves? That seems unfortunate.

**Comment by robertbastian** [comment]
if by round-trip you mean round-trip through YMD then yes. round trip though conversion to other calendars, no, those will always work, round trip through RD also.

**Comment by sffc** [comment]
> I would prefer for there to be a single fundamental range being applied. Perhaps in that case it must be R.D, but that forces us to check R.D. on all construction.

> It's possible to create the max Gregorian date and convert that to Hebrew

I was thinking that we would have a `const ArithmeticDate<Hebrew>` that we pre-calculate to be the RD min/max (with a test) and then we can `<` / `>` against it. No conversion to RD is necessary

**Comment by Manishearth** [comment]
> if by round-trip you mean round-trip through YMD then yes

Yeah. It's a property I am not strongly opposed to losing, but I would like to make sure we acknowledge that we're losing that property.

**Comment by robertbastian** [comment]
> I was thinking that we would have a `const ArithmeticDate<Hebrew>` that we pre-calculate to be the RD min/max (with a test) and then we can `<` / `>` against it. No conversion to RD is necessary

I do not want to have a different range for each calendar, and I do not want the valid range to start in the middle of a year.

**Comment by sffc** [comment]
I think I value "round-trips through YMD" higher than "range boundary is at a year boundary" but I'm willing to be convinced otherwise if we can articulate the pros and cons.

**Comment by robertbastian** [comment]
* Pro: we don't have to document constructors with special years where some days work others don't 
    * Pro: we never return a range error with minimum month or day values other than 1
* Pro: we can document generic Date constructors (from_fields, from_codes) with a single condition for year values (abs(extended_year) < 10e6), instead of one per calendar
* Con: `Date::try_new_from_codes(None, date.year().extended_year, date.month().standard_code, date.day_of_month().0)).unwrap()` might fail

**Comment by sffc** [comment]
> > There's also an assumption I haven't verified that the extended year range is narrower than the RD range in every calendar.
> 
> For example, is the Ethiopic Amete Alem date (-1e6, 1, 1) within the RD range? I think maybe it isn't. Haven't verified 100%.

Ethiopian years have 365.25 days on average. After we add the Amete Alem epoch, which is approximately -2,005,953 (25 March 5492 BC), it follows that the RD of that date is approximately -1e6*365.25 - 2.006e6 = -367.3e6. That RD exceeds the minimum RD.

**Comment by sffc** [comment]
Observation: Not all valid Dates can be created via `from_fields` or calendar-specific constructors.

Observation: The invariant on year can't be used by any external code, since it is possible to create a Date violating that invariant.

Observation: The invariant of `Date::add` an d any `to_calendar` functions needs to be the RD version.

So, what we're saying is that _these specific constructors_ choose to adopt a different (narrower) range because we think it is easier to explain in their docs and because it allows the minimum `month` and `day` to always be 1.

Observation: The following code is not guaranteed to have the same behavior with regard to RangeErrors.

```rust
d1.add(DateDuration::years(1))

Date::try_new_from_codes(None, d1.year().extended_year + 1, d1.month_code(), d1.day())
```

**Comment by robertbastian** [comment]
> Observation: The invariant on year can't be used by any external code, since it is possible to create a Date violating that invariant.

there is no invariant on year. there is a precondition on some constructors that implies the invariant on RD

**Comment by robertbastian** [comment]
> Ethiopian years have 365.25 days on average. After we add the Amete Alem epoch, which is approximately -2,005,953 (25 March 5492 BC), it follows that the RD of that date is approximately -1e6*365.25 - 2.006e6 = -367.3e6. That RD exceeds the minimum RD.

yeah this is fixed in #7220

**Comment by sffc** [comment]
Ok, I'm satisfied if we define that there's only one invariant, the RD range on Date, and separately document on each constructor that they elect to accept a certain smaller year range.

**Comment by Manishearth** [comment]
I think that's good.

**Comment by sffc** [comment]
WG notes:

- @sffc Looking for feedback on https://github.com/unicode-org/icu4x/issues/7076#issuecomment-3488769017. We are defining Date to have a specific RataDie range. The exact range is defined in @robertbastian's pull request; it is on the order of a few hundred million RD, which corresponds to a million years.
- @robertbastian The way I defined it was the RD range is the range that supports +/- a million years in every calendar. The generic constructors enforce a range of +/- a million years, which is smaller than the RD range. It means you can convert between any Date in any calendar, but they don't round-trip through their YMDs.
- @hsivonen Are the aesthetics of having round year documentation for each calendar better than avoiding this weird thing where you can't round-trip dates through serialization? To me, that is more unfortunate than not having round numbers.
- @robertbastian Round-tripping through ISO is more important than round-tripping through YMD numbers. It's better than having different ranges.
- @hsivonen Was there a reason we don't have a single universal range that results in mid-year endpoints?
- @robertbastian Please don't talk about serialization; we don't serialize
- @Manishearth JS serializes by ISO, which we have here
- @hsivonen What I mean is you take the YMD in a tuple and store it somewhere.
- @sffc We serialize through ISO in Temporal. It covers many use cases. Not all use cases. But we don't have a great solution for the non-ISO-based serialization. We would want to build out a good solution for such use cases, perhaps something based on DateFields, which we could still do even if we land @robertbastian's proposal.
- @hsivonen (reiterates that non-ISO-based serialization is motivated due to calendar definitions potentially drifting)

Proposed plan:

- We have a fundamental RD range. try_from_rd clamps.
- We have a per-calendar year range that is *narrower* than the RD range. Calendars constructed from explicit year values cannot use years outside this range
- It is possible to make out-of-year-range dates by converting from another calendar. This is okay.

CC @nekevss

**Comment by Manishearth** [comment]
I think this means code-wise we are fine here, this issue remains open for documenting this behavior.

**Comment by Manishearth** [comment]
This has been discussed, issue is open for documenting (partiall done in #7227, unsure if there's anything left over to do)

**Comment by Manishearth** [comment]
From Shane https://github.com/unicode-org/icu4x/pull/7227#issuecomment-3514028734

> (I do consider tests to be a requirement for shipping this new "feature", but they can be in a follow-up if necessary)

**Comment by Manishearth** [comment]
Triage: This remains in the 2.2 milestone as long as we consider the new date stuff as a headliner milestone item. If that changes, this can become milestone-non-blocking or bumped to a different milestone.

**Comment by Manishearth** [comment]
Current status: [all cross-calendar and per-calendar ctors document valid ranges](https://unicode-org.github.io/icu4x/rustdoc/icu/calendar/struct.Date.html). The valid ranges are different: most enforce a soft year range, but everything is required to conform to a wider RD range.

We do not have extensive tests here, that is the only blocker. Given that the tests do not affect API, I am tagging this as milestone-non-blocking.

**Comment by sffc** [comment]
I really really want to see evidence that all of our APIs implement the bounds correctly. That means all constructors (including From impls) and all fns that modify a date, such as date arithmetic.

**Comment by Manishearth** [comment]
Agreed, but I don't think it rises to the level of being a hard release blocker.

We still want to try and fix this, and probably will, but we currently have a lot of issues that need work here and we must prioritize.

**Comment by sffc** [comment]
I consider it a release blocker if we include the feature in our release notes. Otherwise it's nothing more than an experiment.

**Comment by sffc** [comment]
In other words, right now our release notes should say: "some Date constructors return errors on narrower ranges"

What I want to say is: "Date objects are guaranteed to be in the range X to Y"

**Comment by Manishearth** [comment]
Hmm. I don't actually want us to be making that level of commitment yet, since different routes for producing dates do different things. The RD range is the only fundamental thing here and I think we've explicitly given ourselves license to tweak it.

This might be in line with your "experiment" way of looking at it but I'm actually weakly in favor of having this not be much more strongly committed to than it is right now.

The current docs have a pretty clever way to avoid mentioning an actual RD range: instead they say that constructing from RD may clamp if the RD did not come from `to_rata_die`. Given that all current methods of stably constructing a Date clamp within a calendar-specific year range, and that year range is well within the RD range, this effectively means that that clamping only triggers when manually constructing from RD (that you did not get from another Date), a rare, more "internal" operation.

I think that works well.


The one leftover bit there is https://github.com/unicode-org/icu4x/issues/7207, I think. That's a thing I intend to work on that I consider more of a blocker since it is about fixing panics.

**Comment by Manishearth** [comment]
Actually, no, now that I think about it, the way we handle https://github.com/unicode-org/icu4x/issues/7207 is important for this. The For the current set of stable APIs, the RD range is "basically internal" since it's only relevant for `from_rata_die` when using manually-written RDs. But, if we choose to enforce that range in date arithmetic, we _probably_ should document it.

It can of course still be treated as an "experimental" range for 2.2 (I think that would be fine, it's a really niche thing to need to worry about since these are massive dates anyway) but we'd probably want to eventually commit to a range.

**Comment by Manishearth** [comment]
@sffc and I had more discussion

We noted that `Date::try_new_from_str` currently hits the ISO calendar's year range check; it should not, since this is an interchange format. All constructable dates should be (de)serializable via IXDTF.

The per-calendar year ranges should _only_ apply to `try_new_calendarname` and `try_new_from_fields`. Everyone else (including arithmetic, https://github.com/unicode-org/icu4x/issues/7207) should apply only the RD range.

**Comment by Manishearth** [comment]
- @Manishearth We don't currently do IXDTF serialization. It seems like we make digits that are not IXDTF serializable
- @robertbastian: in the 6-digit shape.
- @Manishearth Given that you must specify a limit according to ISO 8601, and Temporal is the only standard that N=6, that seems like a reasonable answer. Since these are nonsense dates anyway, we should pick the Temporal limit.
- @Manishearth I think we should have the property that all dates ICU4X produces are 6-digit serializable. There are 2 ways to change the RD range to support that.
- @robertbastian You say we need to decide on 4 or 6
- @Manishearth No, we decide on 4 and some number greater than 4, which is 6.
- @robertbastian I think we should be lenient on what we accept; we should accept and produce an arbitrary number of digits. The Temporal limit of 6 doesn't apply to us. Temporal cannot actually create a date that can serialize to something bigger than a 6-digit year.
- @Manishearth Parsing is hard and annoying, and we implement a parsing standard exactly, and the 6-digit thing is part of the grammar.
- @robertbastian The 6-digit thing is something @nekevss implemented. We can change that.
- @Manishearth It's easier to say we implemented that specific grammar
- @robertbastian We don't need to implement the 6-digit grammar. We can implement a flexible one.
- @Manishearth There are 3 grammars. ISO 8601, RFC 3339, Temporal. Temporal supports things from multiple grammars. The variant we implement is Temporal's. ISO 8601 is the only thing that has a pluggable number. RFC 3339 has no extended year opinion. Temporal plugs in the 6-digit year plus annotations. I don't want to introduce a new grammar.
- @sffc ISO 8601 requires a number of digits in the year since the month and day separator can be optional, and you need to know how many digits to expect.
- @Manishearth Yeah, we support that.
- @robertbastian We document it as RFC 9557 parsing
- @sffc Technically RFC 9557 supports only 4-digit years. Since we support 6-digit years, we are not actually RFC 9557. We should technically change the docs to point to the Temporal datetime grammar.
- @robertbastian Jiff talks about supporting RFC 2822
- @sffc That seems to be another date format specified in the email standard, https://datatracker.ietf.org/doc/html/rfc2822#section-3.3
- @Manishearth It looks like jiff doesn't do the extended years.
- @robertbastian Can we do that?
- @Manishearth We have an active contributor who contributed the parser.
- @robertbastian Yeah, but do they use it through `Date::try_from_str`?
- @Manishearth yeah. You're right that if we made the range bigger, Temporal_rs could check the range on their side. Overall these dates are all nonsense.
- @robertbastian Am I correct in assuming Temporal picked 6 digits because that's the range they needed? It feels wrong to pick that range because of their constraint.
- @Manishearth From my research, all I could find for extended years was the Temporal 6 digits. I couldn't find another interoperable standard using something other than 6 digits.
- @robertbastian I don't like accepting 500,000 years. Can we make them accept 10,000 years? It's a power of 10 and it aligns with the 4-digit year in all the RFCs
- @Manishearth Let's talk about solutions. There's a nice property right now, the type validity range, where we have year ranges and RD ranges. The year ranges are pan-calendar, in the sense that the calendar constructors don't let you give more than +/- 1e6 years. Then we have the RD range, where you could start with a date in one calendar and convert it to a date in another calendar even if it exceeds +/- 1e6 years in the target calendar. And the RD range is tight, which is a cool property.
- @robertbastian The RD range is the date invariant. It doesn't need to be tight.
- @Manishearth The two solutions are basically, either we get rid of the tight range so that we have a smaller year range and a 6-digit ISO RD range, or we make the year and RD range smaller.
- @robertbastian What does it give us?
- @sffc We have a number of properties. It's not clear that any of those properties are super compelling. So it seems best to set our limit to the grammar, which is something we can actually point to.
- @robertbastian Okay so what are our constraints? Our RD range needs to be larger than Temporal's 64-bit timestamp range. Our RD range needs to be smaller than +-999999-12-31?
- @sffc: IMO requirements we should not drop: RD range should be >= Temporal actual range (~250k ISO years) and <= Temporal parsing range (~999k ISO years).
- @Manishearth Note that changing it to 100k doesn't work because Temporal uses some of our constructors.
- @robertbastian Which constructors?
- @Manishearth from fields, maybe others.
- @robertbastian The reason we picked this model was to improve docs for constructors by placing limits on era years. On from fields, I'm okay giving it in terms of ISO, because it is more of a power user API.
- @Manishearth I don't think Temporal uses per-calendar constructors. If you want only the per-calendar constructors to check a smaller range, I'm happy, that's great.
- @robertbastian What does Temporal expect us to do if we got outside of their range?
- @Manishearth Error... it's an issue I need to work on.
- @robertbastian Then the range needs to be checked twice, if we have a different range.
- @Manishearth We need to do a pre-check for arithmetic purposes, and then we need a final check.
- @robertbastian What's the actual problem? Temporal needs to check all the dates anyway for their own range.
- @Manishearth ICU4X has debug assertions that fail. Clients need to have deep understanding of our code to uphold our invariants. And eventually we want to add serialization.
- @robertbastian We haven't written down serialization as a goal.
- @Manishearth Or we don't have tight ranges anymore, and we are just more careful on how we deal with things.
- @robertbastian Tight ranges have no value. I picked it because we needed a range. Why 500k? Why not 300k? Or 330k?
- @Manishearth If we in the world of not doing tight ranges, 500k is not a value I've ever picked.
- @sffc We could pick to equal the Temporal RD range.
- @robertbastian The Temporal RD range is on timestamps.
- @Manishearth I think we should pick RD +-999999-12-31, and from fields / arithmetic check RD (and they also pre-check a large year number so that the math works), and per-calendar constructors pick their own year number, I don't care.
- @robertbastian 9999 years.
- @Manishearth Sure.
- @robertbastian If arithmetic needs to check an RD...
- @Manishearth And from codes?
- @robertbastian I'd rather from codes to be well documented.
- (writing conclusion)
- @sffc Any reason to choose 999999 instead of Temporal's range
- @robertbastian: Temporal's range is a timestamp range not an RD range
- @sffc Temporal has a PlainDate type that has a range.
- ...
- @robertbastian Temporal's range is specified as a round number of days, but it's a non-round year.
- @Manishearth The Temporal range is a round RD number. It's just the round RD number is a weird ISO date.
- @robertbastian Main thing is that the errors are bad. Can't do a mid year month error.
- @sffc we have a new error type Overflow without complicated other error types
- @robertbastian I didn't think we decided to add that
- @sffc only Fields and Arithmetic
- @sffc The Temporal RD range: `1. If abs(ISODateToEpochDays(isoDateTime.[[ISODate]].[[Year]], isoDateTime.[[ISODate]].[[Month]] - 1, isoDateTime.[[ISODate]].[[Day]])) > 10**8 + 1, return false.`
- @sffc I don't see why we don't pick that number. It is a nice number to document. It gives us 2 extra bits of wiggle room for arithmetic. It has technical merit. I haven't heard an argument for 999999-12-31 except for it looking nicer in docs.
- @robertbastian And we don't need to add an error variant to try_from_str
- @Manishearth We can use range error
- @sffc I thought we established that we use Overflow error
- @Manishearth I think we didn't establish that
- ...
- @Manishearth Another reason to prefer smaller RD is that some arithmetic operations are slow.
- @robertbastian If you are doing something 4 million times or 1 million times... that doesn't seem to significantly improve performance. Can you demonstrate that?
- @Manishearth If a 4x speed increase is not important to you
- @robertbastian If you have a linear time algorithm then that's a problem that should be fixed
- ...
- @Manishearth I'm happy implementing any RD range decided below and we can change the RD range later

Proposal:

- Date RD range is -999999-01-01..+999999-12-31
    - Returning errors: from fields, arithmetic. This returns a special Overflow error variant.
    - Clamps: from_rata_die
    - Syntax error returned by try_from_str
- Calendar year range is -9999..=9999
    - Enforced by: calendar constructors, try_new_from_codes
- Potentially fix IXDTF docs to be more explicit about Temporal format (file an issue)
- Document RD range on error variants with the range, but be explicit that it is subject to change (potentially by adding an Overflow variant to ParseError), link to issue.

Implementation notes: Arithmetic and from_fields should internally have a pan-calendar year range that we know and is tested to be out of RD range, that is used as a precheck. ~1.2M years, i.e. larger than the RD range for all calendars

Agreed: @sffc, @manishearth, @robertbastian

**Comment by sffc** [comment]
One potentially important difference between 1e8 RD and +999999-12-31 is that 1e8 RD, when associated with a time and a zone, is in range of an i64 millisecond timestamp, whereas +999999-12-31 is not. The "two extra bits" push +999999-12-31 out of range.

**Comment by robertbastian** [comment]
Just to clarify, Temporal's range is not -1e8..1e8 RD, it is +-1e8 since 1970-01-01.

**Comment by sffc** [comment]
I would like feedback from @nekevss and @hsivonen on the proposal above.

**Comment by nekevss** [comment]
I'd agree that IXDTF docs could probably be more explicit on origin. Some of that stems from not having easy access to the ISO 8601 specification. Maybe it's worthwhile to feature flagging some of the functionality? ... I did mention this on in a PR comment somewhere, but there is some serialization logic that can probably be upstreamed soon (potentially different topic).

As for the RD range, I don't have a hard stance either way. I think the Temporal range is already very large, and I'm not entirely sure why any one would want to go much larger beyond support +-1e8 since unix epoch. That being said, it is unix epoch which doesn't make as much sense to apply to a RD range.

**Comment by sffc** [comment]
I closed #7544 as obsolete given the new discussions, but we should go back and make sure this stuff is documented (as well as tested).

**Comment by Manishearth** [comment]
I think all that is left here is documentation and potentially more testing.
